name: fluid_storage
description: Fluid item storage for Flutter.
version: 0.1.0
repository: https://github.com/sharpsan/fluid_storage
environment:
  sdk: ^3.3.4

dependencies:
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
