name: fluid_storage
description: Fluid item storage for Flutter.
version: 0.1.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
