name: fluid_storage
description: Fluid item storage for Flutter.
version: 0.1.0
repository: https://github.com/sharpsan/fluid_storage
environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0

flutter:
